### ISSUE TITLE
Set content-type in S3 for html files

### ISSUE THREAD

**Issue by PiffPaffM** [jonelantha/gatsby-s3-action#20]
Hello @jonelantha,
thanks for making my deployment process so easy! 

I am using the package now for quite some time. Unfortunately, I encountered a strange behavior in the last few dates. AWS is setting the wrong content-type for my HTML files in S3. index.html has now the type _binary/octet-stream_. It should be _text/html_. Is it possible to set the content-type somewhere? Was there any change that could cause that behavior? I could not find anything in the commits. 

Thanks,
Markus

**Comment by jonelantha** [comment]
Hi @PiffPaffM, thanks for your feedback it's appreciated

You're right that there was a recent release but this was mainly documentation and build process updates. Once published the final compiled code didn't change and has been the same for three months: https://github.com/jonelantha/gatsby-s3-action/blob/main/dist/index.js

I tried a test publish and wasn't able to reproduce the issue (I cleared out the bucket first in case that made a difference).

So I think the problem may be related to something changing with your setup maybe? If I look at the  properties of the index.html file in my S3 bucket I see this (Metadata section), I guess you see something different?

<img width="669" alt="Screenshot 2021-01-28 at 18 08 56" src="https://user-images.githubusercontent.com/57597570/106180454-352b0d00-6194-11eb-9845-81fb17547692.png">

**Comment by Akallabet** [comment]
@jonelantha I can confirm I'm having exactly the same issue as @PiffPaffM, the content type header for any html document is now `content-type: binary/octet-stream`

**Comment by Akallabet** [comment]
To confirm the issue isn't related to my S3 configuration, I used the `aws cli` command `aws s3 sync ./public $BUCKET --delete` which works perfectly.

**Comment by PiffPaffM** [comment]
@Akallabet  Thanks for confirming. I also talked to our DevOps people and they did not change anything. 
@jonelantha Could it be related to an update of Gatsby? I am using
Gatsby CLI version: 2.19.1
Gatsby version: 2.31.1

**Comment by jonelantha** [comment]
Thanks for this, I'm keen to try and figure out what it could be.

@Akallabet and @PiffPaffM is there anything in your workflow files which is significantly different to the examples given in the readme? For example like the node version or if anything else going on other than the checkout and the gatsby build?

@Akallabet where you trying `aws s3 sync ./public $BUCKET --delete` from a local environment (rather than from Github actions)?

**Comment by PiffPaffM** [comment]
@jonelantha I updated the whole dev environment. It runs on the latest version. Thanks for your support!

**Comment by jonelantha** [comment]
Thanks for the info, I've updated my own gatsby version to 2.32.2 and I'm still not seeing the issue ☹️ 

Please can check one thing if possible: 

Can you see if the content type is correct on images/css/js files?

I just want to make sure it's just html files affected, thanks

**Comment by jonelantha** [comment]
Also @PiffPaffM, in addition to the question above (about the content type on images/css/js), can you also let me know if all html files have the wrong content type or is it just `index.html` which has the wrong content type?

Thanks!

**Comment by PiffPaffM** [comment]
@jonelantha Thanks for checking! All html files have the wrong content type. Regarding the other files:
js: application/javascript
image: image/png
css: text/css
json: application/json

Everything looks fine except of the HTML files. Could it also be a third party package? I started to check the packages which a lately installed but could not find anything.

**Comment by jonelantha** [comment]
Thanks @PiffPaffM.

Hm, still not completely sure what's going on...

I've just pushed up a version of the component which has extra logging enabled ([here's the diff compared to v1](https://github.com/jonelantha/gatsby-s3-action/compare/v1-debug))

If possible, please can you change your workflow to use this version?

To use this version you'd change the relevant line in the workflow file to:

`uses: jonelantha/gatsby-s3-action@v1-debug` (normally it would be `uses: jonelantha/gatsby-s3-action@v1`)

If you're then able to trigger a deploy there should be a lot more information in the log.

In particular can you check the log to see if it contains `binary/octet-stream` or possibly the text `Unable to guess content type for`(there's a search box at the top of the logs which might help 😄)

Thanks, hopefully we'll figure out what's going on here!

**Comment by PiffPaffM** [comment]
@jonelantha thanks for the new version! That was insightful. It seems that there are two events. The first one seems to be fine. It copies all files from `/public` to my S3 bucket and I can see the `content-type: 'text/html'`. The second event does not make sense to me. It copies files from my bucket to my bucket. There is no content-type header.  Moreover, there are a lot of S3RegionRedirector.redirect_from_error errors which seem to be weird to me.

**Comment by jonelantha** [comment]
Thanks @PiffPaffM, ok that's promising.

Yes the second action is to be expected, it's used to set cache headers - due to the way S3 works you can only do this when creating objects, that's why the copy from the bucket is required.

The errors aren't expected though, I'm not seeing those on my side. 

The solution,  I think, will be to adjust how that second step works.

Would you be able to post a handful of those log entries you mentioned? (please do remove or modify anything sensitive in there)

**Comment by GenisDiaz** [comment]
I subscribe to this issue, I'm having the same problem.

**Comment by jonelantha** [comment]
Hi @PiffPaffM, @GenisDiaz , @Akallabet 

I've just published a beta version which I hope fixes the issue

This version explicitly sets the content type in the second copy phase ([diff here](https://github.com/jonelantha/gatsby-s3-action/compare/v1-content-type-fix))

You can try out the fix by changing your workflow file to use the beta version:

`uses: jonelantha/gatsby-s3-action@v1-content-type-fix`
(instead of `...@v1`)

If this fixes the issue for you I'll move these changes into the main branch 😄

**Comment by PiffPaffM** [comment]
@jonelantha The change is working for me. Thank you very much! That is a big relief.

**Comment by jonelantha** [comment]
That's really good to hear.

It may take a day or two to get that change into the main v1 branch so feel free to keep using that version until then, hopefully won't be long

**Comment by GenisDiaz** [comment]
@jonelantha yeah! for me too. Thanks so much for your effort.

**Comment by jonelantha** [comment]
I've now merged these fixes into the main v1 branch so it should be ok to start using `jonelantha/gatsby-s3-action@v1` again (but I'll leave the `v1-content-type-fix` branch up for now)

Many thanks everyone for feedback to help to help fix this 👍
