### ISSUE TITLE
Only upload changed files

### ISSUE THREAD

**Issue by craigbloodworth** [jonelantha/gatsby-s3-action#34]
I've a site which builds 6000+ pages. Is it possible to detect which pages have been modified and only upload those? Current GitHub action time is about 5 minutes to upload anything. Any way to optimise this would be greatly appreciated

**Comment by jonelantha** [comment]
Hi, the problem is that the S3 sync has no easy way to figure out if a file should be updated. Currently it checks to see if the file is newer or if the size has changed. When building the site on GitHub before the sync, all the files will have a newer date than what's in the bucket, so all the files gets uploaded.

I can experimentally add an option so that if the file size hasn't changed then the file won't be copied. This should cover 99% of files but the problem is that files which were updated but stayed the same size would be missed from the copy. For example editing one letter on a page would change the content but not the page size, so might be missed in the sync.

I can't think of any other solutions but I think some of the Gatsby hosting can handle incremental changes if that's useful?

**Comment by craigbloodworth** [comment]
Hi, yes I think the size only comparison would be useful as a option. In my case the bulk of pages never change as they're one time blog posts. The greatest amount of change therefore is from new blog posts and major page changes, both of which would be covered by the use case and greatly optimise the build.

Gatsby hosting did handle incremental change yes but they're shutting down their service as they move to Netlify which doesn't push sites to S3 hosting.

**Comment by jonelantha** [comment]
v2.1.0 should address this

Please try adding `only-size-changed: true` to your existing gatsby-s3-actions options 🙂
